### ISSUE TITLE
Total volume calculation incorrect

### ISSUE THREAD

**Issue by acratw01** [astashov/liftosaur#103]
The bulgarian split squats requires both legs to do the reps and weight for each set. Example: 3 reps @ 120 lbs on left leg and right leg so total volume is 720 lbs for both legs. 

The total volume calculation doesn't account for both legs and only calculates the total volume as 360 lbs for the set. 

I believe this is a global issue and probably impacts other similar exercises.

**Comment by astashov** [comment]
You can currently separate sets to left/right leg, then you'd get volume right.
But also - is that a big deal? I always considered absolute volume number being pretty useless - more important is trend IMHO - whether it goes up or down week over week.

**Comment by acratw01** [comment]
Thanks for the reply. I didn't realize sets could be separated, I'll look
into that. Absolute volume is probably useless but it was annoying me that
it wasn't right.
