### ISSUE TITLE
Update CSV import to work correctly with new Equipment paradigm

### ISSUE THREAD

**Issue by evilrobotfromouterspace** [astashov/liftosaur#105]
As a user, I want to be able to import exercise history via CSV and have continuity in history tracking across imported exercises and new programs, so that I can switch from Strong to Liftosaur and accurately track my progress over time.

Given I prepare a properly formatted CSV import with history from another data source
1) When I upload the CSV import into Liftosaur
Then I see the history
(this appears to work mostly correctly)

2) When I perform a custom exercise in Liftosaur
Then it matches the custom exercise I uploaded via CSV for the purpose of history tracking
(this appears to be broken)

Artifacts:
A Custom Exercise I created via the UI for Paused Squat. I am not given an option to select Barbell when creating the Custom Exercise.
![image](https://github.com/user-attachments/assets/35307672-19a9-4eac-90f7-d7de3a398628)

An example of CSV imported exercise session
![image](https://github.com/user-attachments/assets/b5174c3a-3957-4675-8567-a86319d840fa)

Clicking on Paused Squat shows the imported history of Paused Squat
![image](https://github.com/user-attachments/assets/0a854ea4-170b-4359-83bb-3b9b44b68ec9)

**Comment by evilrobotfromouterspace** [comment]
[Liftosaur Import 2024-07-28 - Sheet2.csv](https://github.com/user-attachments/files/16484384/Liftosaur.Import.2024-07-28.-.Sheet2.csv)
Adding example csv import I used

**Comment by astashov** [comment]
Yeah, need to fix and remove equipment stuff from the CSV import/export. Done!
