### ISSUE TITLE
Custom Exercises Broken

### ISSUE THREAD

**Issue by yashrastogi** [astashov/liftosaur#107]
After recent updates the custom exercises feature has become broken, the custom exercises are present but in program editor it is saying "Error: Unknown exercise <name> (21:0). Add custom exercise"

![image](https://github.com/user-attachments/assets/1c7a48a3-4647-4a7e-bfea-cfd23a292b05)

**Comment by astashov** [comment]
It was frankly broken before, and the fix invalidates some existing exercises.
In the program, the exercise name is "Single Leg Calf Press, Leverage Machine", but your custom exercise name is "Single Leg Calf Press".

Curious - if you rename the custom exercise to "Single Leg Calf Press, Leverage Machine" - does it fix the issue?

**Comment by astashov** [comment]
Also, what's your user id? I can take a look under your account

**Comment by yashrastogi** [comment]
id: rqulpzcvyw

I thought the equipment is separate from the exercise and doesnt need to be explicitly mentioned during creation of the exercise?

Yes, renaming the custom exercise to "Single Leg Calf Press, Leverage Machine" works.

**Comment by astashov** [comment]
Yeah, equipment is separate from the exercise, so "Single Leg Calf Press, Leverage Machine" actually being treated as "Single Leg Calf Press" with the equipment "Leverage Machine" was a bug. Custom exercises shouldn't have equipment assumed/associated, and only should have the name. So, "Single Leg Calf Press, Leverage Machine" or "Single Leg Calf Press with leverage machine" or "Single Leg Calf Press" is just a name.

**Comment by yashrastogi** [comment]
Oh, got it! Thanks.

Great application by the way!

**Comment by astashov** [comment]
Thanks :)

**Comment by yashrastogi** [comment]
@astashov the 1rm value for my custom exercises have been reset, for some I remembered the value and set it manually for others is it possible to restore it from history?

**Comment by astashov** [comment]
@yashrastogi like for all of them? How did it happen? Any specific actions you did?
I probably can restore them from a backup, or you can also **kinda** get them from the estimated 1RM graphs (but it won't be the same...)

**Comment by yashrastogi** [comment]
For some custom exercises I had just saved the 1rm value and not logged any workouts with it.
I guess in the database the 1rm was being stored for the custom exercise + equipment name  (how I initially thought it was supposed to be, even for custom ones) so for eg. I wanted the last 1rm value for JM Press custom exercise but I guess it was saved under JM Press, Smith Machine and when you disabled equipment for custom exercises it got reset.
