### ISSUE TITLE
Sets for Complexes?

### ISSUE THREAD

**Issue by eburley** [astashov/liftosaur#109]
I'd like to be able to create complexes. My use case is a Kettlebell program where the proscribed workout is sets with 2 KB cleans, 1 KB press, 3 KB squats in an EMOM. I can certainly template the individual exercises together, but I'd prefer being able to define a complex exercise and then express it using existing notation. 

Here's a straw man:

```
abc: Clean, Kettlebell / 1x2 /  warmup: none/ 20kg / used: none
abc: Push Press, Kettlebell / 1x1 / warmup: none/  20kg / used: none
abc: Front Squat, Kettlebell / 1x3 / warmup: none / 20kg / used: none

complex:abc / 10+x1 / 20s 20kg
```

This would program 10 rounds of clean, push press, front squat with 20 seconds in between rounds. The weight in the complex would override the weight in the template.

**Comment by astashov** [comment]
That frankly would complicate Liftoscript quite a bit, so probably won't do it for now, sorry.
