### ISSUE TITLE
Weight rounding does not function properly after 'update:'

### ISSUE THREAD

**Issue by tsvng** [astashov/liftosaur#167]
I use an update: scheme where if I go below 5 reps on a set, my following set reduces by 10% in working weight.

It seems that the rounding does not function properly in this scenario, as the exercise is set to have a rounding of 5lb increments.

Please see these 2 instances below on when this occured with Seated Row + JM Press exercises.

Here is my update code block:
```
update: custom() {~
  if (setIndex!=0 && completedReps < minReps){
    weights= weights[setIndex]*0.9
    }
~}
```
Seated Row expectation was to go from 140 lb -> 125 lb, instead was stuck  at 126 lb
JM Press expectation was to go fram 80 lb -> 70 lb, instead was stuck at 72 lb
![Liftosaur Seated Row Weight Rounding Bug](https://github.com/user-attachments/assets/77860bb2-2e97-4fad-b666-a7783c8271d6)
![Liftosaur Seated Row Default Rounding](https://github.com/user-attachments/assets/32a848de-d3a0-4d6e-9e1a-b8e87d91b269)
![Liftosaur JM Press Rounding Bug](https://github.com/user-attachments/assets/41618e5d-3589-4390-98bf-94811b2b8a85)
![Liftosaur JM Press Rounding](https://github.com/user-attachments/assets/fbcc2b48-84fa-4367-b681-f99ebf044f9f)

**Comment by astashov** [comment]
Fixed, thanks for reporting!
