### ISSUE TITLE
Add program templates to this repo?

### ISSUE THREAD

**Issue by marcelmindemann** [astashov/liftosaur#180]
Hi astashov,
thanks a lot for this great app!
I was looking for the liftosaur scripts for popular programs like GZCLP, TheRippler etc. in this repository because I wanted to correct some small deviations from the original source. However, I cannot find them anywhere - are they not part of this repo? It might be that I am simply too dumb to find them. If they are not part of the repo, would it be possible to add them?

**Comment by astashov** [comment]
Hey!

No, they're not part of the repo, they're stored in the database.
But you can find them and edit them if you clone the program. Go to "Choose Program" screen, clone a program you like (e.g. GZCLP). Then, go to Program screen, and tap on the paper icon - and you'll be able to see the script.

Or there's "copy link" at the bottom of the "Program" screen in the app, tap it, and then paste that link to e.g. Chrome, and you can edit it on the desktop.

Or you can log in in a browser on your laptop, then go to "Your Program" and also find it there :)

**Comment by marcelmindemann** [comment]
Hey,
I know how to edit _my own_ programs, I was talking about the default templates that new users receive when they clone a program. E.g. the Liftoscript code that you wrote here: https://www.youtube.com/watch?v=1sOr8pS9tl4
Is there a reason you haven't added those default templates to the repo?

**Comment by astashov** [comment]
> I know how to edit my own programs, I was talking about the default templates that new users receive when they clone a program.

But same thing - if you don't want to clone the program to your account to see the code - open https://www.liftosaur.com/app in Chrome in Incognito mode, clone the program (e.g. The Rippler), go to Program and copy the link above. Then, open the link in the new tab.

You can tap the paper icon there to see full text (not splitted by week/day).

> Is there a reason you haven't added those default templates to the repo?

It's just easier to keep them in the database instead of the source code. Fastesr to tweak, I don't need to redeploy the whole app, behave the same as the user programs, etc.

**Comment by marcelmindemann** [comment]
Ah, I see. Yeah, redeploying the whole app for a content change is unnecessarily slow. What I usually do is keeping such content in the git repo, and have a special Github Actions workflow that syncs that folder with the database. That way I circumvent frequent redeploys, but still have the benefit of version control for my textual content. Of course I respect your way of working, it's your app after all :) Thanks for taking the time. Issue can be closed.
