### ISSUE TITLE
Google Login and Workout Sync Failing

### ISSUE THREAD

**Issue by yashrastogi** [astashov/liftosaur#182]
Since a few hours there some issues with syncing and Google sign in, both are failing.
![image](https://github.com/user-attachments/assets/0f2f67e4-a659-4ee5-b477-817afe1659c0)

**Comment by codetyper** [comment]
Same here.

**Comment by mattstratton** [comment]
Anton posted this in the Discord:
> Yup, site is down, looking into it! You can use the app, it'll sync when the site is up

**Comment by astashov** [comment]
Hey!

The servers were down, sorry! It should be fixed now!
