### ISSUE TITLE
Weight rounding does not function correctly when mixing kg/lb equipment

### ISSUE THREAD

**Issue by tsvng** [astashov/liftosaur#196]
I primarily use lbs for all of my exercises in the gym except for calf raises where I hold a kettlebell which uses kgs.

When I input 24 kg as the working weight, Liftosaur automatically rounds it to 54 lbs.

Here you can see I set the weight to 24 kg.
![Liftosaur Calf Raise Weight Setting](https://github.com/user-attachments/assets/bdd8a63a-230b-4a6f-a176-ec37edbc4098)

And here you can see it gets rounded to 54 lb
![Liftosaur Calf Raise Rounded](https://github.com/user-attachments/assets/e759e0ef-7ce3-436d-922c-bf239e494fb7)

**Comment by astashov** [comment]
Yeah, because you have the default unit selected in settings as lbs.
You can set "Kettlebell" equipment to your "Standing Calf Raise", and in the equipment settings set unit to kg, then it'll track it as kg.

**Comment by tsvng** [comment]
You're absoluitely right! Was resolved after changing exercise equipment type to 'Kettlebell', and then going into Settings>Equipment Settings>Kettlebell>Unit>kg
