### ISSUE TITLE
Copy from previous program 

### ISSUE THREAD

**Issue by jm96441n** [astashov/liftosaur#31]
Currently the application allows for copying from preset list of programs, it would be really helpful to copy from a previous program that you've created. If this sounds in line with what you've got planned I can do some work on it (my ts/js is a little rusty but I should be able to handle it)

**Comment by astashov** [comment]
You can do that now in the liftosaur.com/program editor. Just select the exercises, Cmd+C, and then open another liftosaur.com/program tab, and Cmd+V there.
