### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by gilice** [astashov/liftosaur#33]
Hello!

I have noticed that this project, although it claims it's open source (and the code is available) doesn't include an open-source license (or I haven't found it). 

Can you please decide on one and add it?
Eg. From https://choosealicense.com/, something like MIT or GPL are popular choices. Thanks.

Cc @astashov

**Comment by riceicetea** [comment]
@astashov cc again because of recent activity in the repo

**Comment by gilice** [comment]
@astashov bump

**Comment by gilice** [comment]
@astashov I realized the addition. Thank you!
