### ISSUE TITLE
After the new update, closing the app with an on-going workout deletes that particular workout

### ISSUE THREAD

**Issue by raymondyew** [astashov/liftosaur#34]
Sometimes, I don't finish my workout sessions and I leave it on-going until the next day and I close the app. The next day, I would open the app with the previous session still on-going and finish the workout session.
After the new update, if I close the app with an on-going session active, it ends the session and doesn't record it. 
Love the app by the way! I just have this small issue with it.

**Comment by astashov** [comment]
Ugh, that's bad. Thanks for reporting, I'll take a look!

**Comment by astashov** [comment]
I think should be fixed now, lemme know if it still happens!
