### ISSUE TITLE
App upgraded but features now are behind paywall

### ISSUE THREAD

**Issue by krillin666** [astashov/liftosaur#35]
Hi @astashov !

I used your app pretty much daily from March to August of last year. I now went back to the gym and noticed your app had some updates in the Play Store. I promptly updated the app to find that it now is rocking a really beautiful and upgraded UI.
Plus, it's finally a native Android app. Congratulations on these upgrades, really.
However, to my dismay, I found that the essential features of the app that I was accustomed to use are now behind a paywall that's actually too steep for me to pay.
I did not find anything on this repo or any type of announcement regarding this paywall, so it would be nice to have been notified.

Thank you.

**Comment by gilice** [comment]
Hey @krillin666 ! I am not the author, but I have received a premium code for the app, to the email address I registered with.

**Comment by krillin666** [comment]
> Hey @krillin666 👁canonical: [github.com/krillin666](https://github.com/krillin666)×?sources : promnesia_sean.sources.mailFrom: Zhenbo Li <notifications@github.com> To: Endle/fireSeqSearch <fireSeqSearch@noreply.github.com> Subject: Re: [Endle/fireSeqSearch] Support custom search engines (Issue #18) @krillin666[/home/mirador/data/mail/ImapMail/outlook.office365-1.com/INBOX](editor:///home/mirador/data/mail/ImapMail/outlook.office365-1.com/INBOX)07/01/2023, 22:00:00 ! I am not the author, but I have received a premium code for the app, to the email address I registered with.

Thanks for the tip @gilice, unfortunately I do not use Google or Apple thus I was never able to register unfortunately (that's why I created https://github.com/astashov/liftosaur/issues/26). So that should be the reason I never received such email 🙂

**Comment by astashov** [comment]
Hey @krillin666 could you send me an email to info@liftosaur.com?

**Comment by krillin666** [comment]
> Hey @krillin666 could you send me an email to [info@liftosaur.com](mailto:info@liftosaur.com)?

Sent you an email! Thanks 😄
