### ISSUE TITLE
Cannot import data/program

### ISSUE THREAD

**Issue by krillin666** [astashov/liftosaur#36]
Hi @astashov,

I'm testing the updated app on Android but I cannot import my data backup from the PWA into the android app. 
The problem is the following: when I click either the `import data from file` or `import program from file` **nothing happens**. There no dialog popup or anything.

I suspect this could be a permission problem since I'm on Android 13 (GrapheneOS), but liftosaur never prompted for storage permissions.

Thank you!

**Comment by astashov** [comment]
Should be fixed now, thanks for reporting! You'll need to update the Android app.
