### ISSUE TITLE
Squat Form for the Squat Image is Funny

### ISSUE THREAD

**Issue by raymondyew** [astashov/liftosaur#38]
The images for the squat have a funny form where the bar doesn't touch the upper back and floats above it to only rest in the fist 😂
https://www.liftosaur.com/externalimages/exercises/full/large/squat_barbell_full_large.png

![image](https://user-images.githubusercontent.com/70300363/217435293-f786d25f-e33d-4464-9990-c1a7c33bcf84.png)

**Comment by astashov** [comment]
Oh yeah, levitating squat, really hits not only your glutes, but also back and triceps. :)
Seriously though, I never even noticed!
