### ISSUE TITLE
[Feature Request] Create/remove sets programmatically

### ISSUE THREAD

**Issue by columndeeply** [astashov/liftosaur#39]
Hi! First of all: thank you so much for making this app, it's been great so far.

I've programmed the Jacked and Tan 2.0 workout and everything works fine with one exception: on the last weeks of each cycle the program adds a few more sets to a couple exercises. Right now I've added sets with 0 reps and just plan on filling them with 0s until they're needed but it would be great if there was a way to remove/hide those sets until they are required.

Here's what the program looks like on excel. The blue cells are extra sets that are only used on week 4 and 5:
![maim_20230422_071633](https://user-images.githubusercontent.com/106948293/233764134-9083a761-e4b8-473e-a99d-e202b1e8d2e9.png)

**Comment by astashov** [comment]
Yeah, you can use "set variations". There's a checkmark you need to enable in the program exercise. Then, you may create several set variations, and there's a "condition" field, that will decide when to use what set variation.

So, for your case there'd be 3 set variations, for 4 sets, 5 sets and 7 sets. You can use week number (or day number) to decide on which to use. Like this: https://www.liftosaur.com/p/21a8e15a

If you share your program (in the app, there's a way to do so from the edit program screen, there's a "edit on a laptop" link at the top, which will copy the program link to the clipboard), I can show you how to integrate that with your program. If you want :)

Hopefully that helps!

**Comment by astashov** [comment]
I'm currently working on a new feature "Dynamic Sets", which would be a bit more flexible and will allow to define logic for dynamic number of sets, but for now "Set Variations" feature should work too.

**Comment by columndeeply** [comment]
Thank you so much! Not sure how I missed the variations button... It's working great now.

Another quick question: is there a way to create a set with an unknown weight? JnT2.0 has a set every week where you've to find a RM for that exercise. I couldn't find a way to edit the weight for that one set once I've completed it. I've tried doing it with a state variable set to "User Prompted" but I can't quite get it working.

**Comment by astashov** [comment]
User prompted variable would be asked at the end of the all sets, so if that's your case - it may work.

You can also edit weights of existing sets by tapping on the edit icon, and then selecting - "Only in this workout", like this: 
<img width="345" alt="image" src="https://user-images.githubusercontent.com/12795/233849723-bd483c11-7717-465a-b211-8a425d9e76c3.png">

> JnT2.0 has a set every week where you've to find a RM for that exercise

Could you please describe how it works? You have to do more and more sets and increase weight each time until you hit 1RM? So you don't know how many sets you'd need upfront?

**Comment by astashov** [comment]
Okay, I read about the Jacked & Tan 2.0 program. So, AFAIU, you e.g. need to work up to 10RM as a first set.
You could probably do it this way - create 2 variables, with `lb` or `kg` type - `tm` and `repmax10`. For `repmax10` value, make a guess for 10RM weight. Then, work up to 10RM by warmup sets. If you were off with your 10RM guess, and it took more/less than e.g. 3 warmup sets, add/remove warmup sets if necessary.

After you figured the 10RM, mark the set as completed, and update the weight of `repmax10` by clicking "Edit" icon.

So, something like this: 

https://user-images.githubusercontent.com/12795/233860010-320b4d2a-3ee7-4651-8cb5-48a55c3f75f9.mp4

What do you think?

**Comment by columndeeply** [comment]
Thank you so much! That's exactly what I was trying to do. I'll reprogram it to use the two different variables and give it a go.

Thanks again for everything!

**Comment by astashov** [comment]
No problem, happy to help :)

**Comment by astashov** [comment]
@columndeeply  That's the exercise from the video, btw, if you need it: https://www.liftosaur.com/p/1ed6a041

**Comment by astashov** [comment]
@columndeeply hey, btw I just started Jacked & Tan 2.0 myself!
This my program implementation: https://local.liftosaur.com:8080/p/10558f87

**Comment by columndeeply** [comment]
Nice! I've been running it for almost six months now and I've been enjoying it a lot. Once you get used to the volume it's great. I was doing a PPL before it and the volume was much much lower, the first weeks of JnT2.0 where harsh AF

The link points to a local copy of liftosaur :D I tried using that ID on the live site but it returns a [404](https://www.liftosaur.com/p/10558f87). I'd love to see how you programmed it tho, I still think my implementation is kinda wonky and might steal some ideas from yours.

I was actually editing it today since I'm almost done with my cut. Here's what I'm planning to do next: https://www.liftosaur.com/p/8741c36e (ignore the weights, most of them are wrong from copy/pasting the exercises and testing stuff).

**Comment by astashov** [comment]
@columndeeply yikes! Sorry, didn't notice I copied the local version :)
This is the real one: https://www.liftosaur.com/p/38ef97e9

Yeah, I'm only doing first week, and the volume is harsh :) We'll see how it gonna go once I move to smaller RMs/higher weights.

**Comment by columndeeply** [comment]
Thanks! You get used to the volume pretty quickly, on my second run those first weeks weren't nearly as hard.

I like the idea of using one variation each week instead of doing calculations with a "multiplier" variable like I was doing. I'll probably redo mine using your format :D
