### ISSUE TITLE
[Feature request] Add a "finish later" button to workouts

### ISSUE THREAD

**Issue by columndeeply** [astashov/liftosaur#45]
Hi! I'd love to have an option to pause workouts and finish them later. Right now I can click on the "Finish workout" button and edit it later but the workout duration counter gets updated and I end up with >15h workouts lol. It's not a big problem since (afaik) that info isn't used in the stats or anything like that but it would still be cool to keep the workout duration to the real time spent working out.

Having an option to pause a workout and resume it later on without it affecting the workout duration would be great.

**Comment by astashov** [comment]
There's now a way to tweak the duration of past workouts
