### ISSUE TITLE
[Feature Request] - Weekly Schedule

### ISSUE THREAD

**Issue by AdamGoertz** [astashov/liftosaur#47]
I love the concept of this app. The flexibility of being able to program the progression scheme for workouts is amazing. 

The big major feature I feel is lacking still is the ability to create customized weekly schedules for each workout program. For example, to specify a Push/Pull/Legs routine that runs 6 days/week on Mon/Tue/Wed/Thu/Fri/Sat, with Sunday off. This would ideally couple into notifications and enable you to set reminders for specific times to start a workout.

**Comment by astashov** [comment]
Hey! You can name workouts like "Week 1 - Monday", "Week 1 - Wednesday", would that be enough? I guess it the reminding part wouldn't work with that though...

Curious, what would you use the weeks for, except for the reminders?

**Comment by astashov** [comment]
I guess one big need for weeks would be to properly track muscle volume and fatigue.

**Comment by AdamGoertz** [comment]
Yes, I think from the weekly schedule, the reminders and tracking statistics over longer periods of time would be the main benefit. 

I suppose I also see this as an incremental step towards an even greater degree of control over workout programming on a more macro scale, which would require much more effort to implement.  For example, I might divide my workouts into several high intensity weeks followed by a deload week, or in rotating multi-week blocks with different exercise variations. It would be useful to represent those higher-level abstractions in a schedule that can modify its constituent workouts rather than baking specific logic into each exercise. 

Obviously, that’s well beyond the scope of what I stated above, but I see this as a step on the path toward that vision.

**Comment by astashov** [comment]
> I suppose I also see this as an incremental step towards an even greater degree of control over workout programming on a more macro scale, which would require much more effort to implement. For example, I might divide my workouts into several high intensity weeks followed by a deload week, or in rotating multi-week blocks with different exercise variations. It would be useful to represent those higher-level abstractions in a schedule that can modify its constituent workouts rather than baking specific logic into each exercise.

Yup, that's a good point. It's actually kinda possible already, usually I just create a `week` state variable, and program different intensities and set schems based on it. As an example - [GZCL: The Rippler](https://www.liftosaur.com/programs/gzcl-the-rippler) program, which is a 12-week program with 3 mesocycles.

**Comment by astashov** [comment]
I guess I can close it since there's multi-week program support now
