### ISSUE TITLE
[Feature Request] -- Improve support for cardiovascular exercise

### ISSUE THREAD

**Issue by AdamGoertz** [astashov/liftosaur#48]
This app could also be very useful for tracking and programming progression in cardio (in addition to weight lifting) with a few small tweaks. 

* Add time (sec, min) and pace (min/mi, min/km) to units
* Allow the user to specify time or distance instead of number of reps, and use the timer to track duration of exercises
* Allow user to specify pace instead of weight
* Add more common cardio exercises to built in list of exercises (cycling and rowing are already present, some other common ones include running, swimming, jump rope, etc)

**Comment by astashov** [comment]
Hey, thanks for the suggestion! It makes total sense, but that's aslo a pretty big feature, so not sure when/if I get to this frankly...

I'm currently trying to focus on deeper weightlifting features (like I'm going to add tracking volume, volume graphs, better RPE support, moving average graphs, better warmup support, etc, etc). Also, I'm going to work on weightlifting workout planner, so you could build your own weightlifting programs and make sure all your muscle groups are properly covered, with enough volume, intensity and frequency.

Want to make it a really good weightlifting app before trying to start tackling other stuff :)

**Comment by AdamGoertz** [comment]
Workout planner sounds great!

I totally get wanting to stick to a particular area of focus before diversifying. I do think this feature would be pretty useful, especially for people (like me) who want to do multiple forms of exercise and manage everything from a central place. 

Just wanted to get the idea out there, thanks for an awesome app!

**Comment by astashov** [comment]
Yeah, I really appreciate the ideas and feature requests! Especially when they're well laid out, with a list of specific features like in your example vs just simple "do cardio tracking" :P

**Comment by Dieterbe** [comment]
Note: I'm right now only a PT in training so the below may not be exactly accurate...
But my current understanding is that 
you can also improve your cardio through your weightlifting workouts by basically doing high intensity with less rest. But I think these improved cardio gains come with reduced strength / hypertrophy gains. I'm new to liftosaur but I'm not sure if the strength progression system takes into account which "style" you use in a workout, perhaps there's no need to consider this. But even without doing explicit cardio, lifting weights should improve your cardio a bit, and more so if you do HIIT lifting. So without (or in addition to) dedicated cardio exercises. Likewise your lifting performance (and gains) in the gym may be partially driven by improved cardio, in addition to improved neurological function and muscle mass. Just something to keep in mind when considering "strength"

What this all means in terms of (potential) functionality in liftosaur, I'm not sure 😃

**Comment by astashov** [comment]
Added "Add better support for time-based exercises" to the roadmap
