### ISSUE TITLE
Equipment resets when importing a program

### ISSUE THREAD

**Issue by columndeeply** [astashov/liftosaur#53]
When importing a program the equipment available resets to the default values. Here's a video showing the process I did to trigger the reset: https://github.com/astashov/liftosaur/assets/106948293/4b7a7117-bb4f-4b6e-b9cf-fdcdd8f12213

I'm using a local account, not sure if that matters.

**Comment by astashov** [comment]
Fixed by 0b2db4ec71f67eb3ec829859274b6aa8a0ed1559. Now it only is going to export custom equipment when copying a link to the program, not all equipment, to avoid accidental built-in equipment overrides.

**Comment by astashov** [comment]
Thanks for reporting! :)
