### ISSUE TITLE
[Feature Request] - Assign different rest times per exercise

### ISSUE THREAD

**Issue by JostLuebbe** [astashov/liftosaur#54]
Hello, I want to start by saying this is an amazing app and it's definitely helped me get back into the gym.

One feature I would love to have is the ability to assign a different rest time for each exercise. So for example, for squats I might want to rest 3 minutes between each set but for dumbbell curls only 1 minute. The existing timers for warmup/workout are good but I always have to do the manual adjustment of adding or removing 15s at a time to get the actual rest time I want.

Thanks again for all the work you've put into this app!

**Comment by astashov** [comment]
You can currently assign per-exercise rest timers, they have precedence over global workout timer.
For that, go to edit exercise screen -> Advanced -> Scroll down to "Extra Features" -> toggle "Enable Exercise Rest Timer".

You can specify both regular number as seconds (e.g. `90`), or you can specify Liftoscript expression, use state variables, etc - same as in reps and weight fields for sets.

Thanks for using Liftosaur! :)

**Comment by JostLuebbe** [comment]
Ah OK, I found it. Thank you for making me aware of this feature.

**Comment by benallan** [comment]
Hi @astashov, is it still possible to use different rest times per exercise in the current ios app? I saw this post, and the reddit one below, but the UI seems to have changed quite a bit since then!

https://www.reddit.com/r/liftosaur/comments/1216cge/added_perexercise_rest_timers/

**Comment by astashov** [comment]
@benallan, sure, either add it to the program text like `Squat / 3x8 100lb 120s` (i.e. that `120s`) would be the rest timer. Or in the UI - swipe the set during editing program exercise, and set the timer there. You can also set the timers globally across all sets on the "Across all weeks" tab.

**Comment by benallan** [comment]
Thanks @astashov.

My first mistake was swiping in the UI before I had added a timer in the liftoscript. After adding any timer to the script, I can swipe and edit fine.

I'm still not sure how to set the per-exercise rest timers _for warm ups_ though, e.g. this doesn't seem to be allowed:

```
Bench Press / 3x10 / 120s / warmup: 1x5 30%, 1x5 50%, 1x5 80% 30s
```

The 30s is an error. Adding a slash before the 30s removes the syntax error, but I can't see the rest timer actually applied.

Sorry I can open a new ticket if this is off-topic now!

**Comment by astashov** [comment]
Yeah, for warmups it's currently not allowed
