### ISSUE TITLE
When editing a program hitting Ctrl+Z deletes all days/excercises

### ISSUE THREAD

**Issue by columndeeply** [astashov/liftosaur#55]
Hi! I was trying out the multi-week program builder (great feature btw, it's going to simplify my current program a lot. No more having a "week" variable on each exercise lol) and I made a typo, I hit Ctrl+Z and the whole program got reset.

I'm attaching a video below but basically what happens is: if you hit Ctrl+Z at any point on the program creation screen the whole program gets reset (I think it creates a new one? Just realized that on my video once it resets the id changes...). It happens even if you have clicked "Save" when creating an exercise, it just wipes everything out.

I'm not sure if it happens on all browsers, I'm running Firefox 117. Not sure if it was happening before or if it's a new bug either.

Here's a quick video: https://github.com/astashov/liftosaur/assets/106948293/191e8678-9284-499d-b74d-16ccf8de6872

**Comment by astashov** [comment]
Ugh, nasty. Will look into it, thank you!

**Comment by astashov** [comment]
Should be fixed now!
