### ISSUE TITLE
Logged workout reps  are deleted when making changes

### ISSUE THREAD

**Issue by amb1s1** [astashov/liftosaur#63]
The app is deletes the logged workout repetition when changing the last rep during workout. This can be frustrating because the user has to start over again.

Steps to Reproduce:

Log a workout rep.
Make changes to the last rep weight.

Expected Behavior:

The logged workout rep should be retained, even when the user is making changes.

Actual Behavior:

The logged workout rep is deleted.

Screen Capture:

https://share.icloud.com/photos/07azxpRyUOIJpMz8Tgi0PSvSQ

**Comment by astashov** [comment]
Fixed that
