### ISSUE TITLE
[Feature Request] Workout planner syntax for adding exercises to existing plans

### ISSUE THREAD

**Issue by ozanmakes** [astashov/liftosaur#67]
First of all, thanks for creating Liftosaur! Programming with it is a breath of fresh air and so intuitive compared to all the other apps I've used. Workout Planner is so well thought out I couldn't believe it.

I've had a great experience planning my workouts with the [Workout Planner](https://www.liftosaur.com/blog/posts/launched-workout-planner/) page. I find this syntax for creating a workout super convenient, compared to creating each exercise using the UI which takes a lot of clicks.

As I  plan my workouts one or two days at a time, I would like to be able to use the Workout Planner syntax to add new exercises to a day and/or new days to a plan. As far as I understand it, right now Workout Planner requires you to define your entire plan in one go and you can't go back and forth from Liftosaur to Workout Planner if you prefer the text-based way of planning.

Is it possible to add an alternative to <kbd>Add new day</kbd> and <kbd>Create new exercise</kbd> buttons that opens up a text input where I can input my exercises and create them in one go?

**Comment by ozanmakes** [comment]
I think the one-liner syntax for adding exercises to a day is still valuable. One aspect of Liftosaur I _love_ is that I can plan my workouts on a laptop quickly, and track them with mobile phone. Workout Planner syntax takes advantage of having access to a keyboard, and feels really quick.

With a keyboard driven menu it would be even easier. I would really like to be able to press [Cmd-K](https://cmdk.paco.me/) <kbd>Add exercise</kbd>, type in `Bench Press / 5 @8, 3 @9, 1 @10, 5x5 50%` and press enter to have the exercise inserted into the day I'm editing.

**Comment by astashov** [comment]
Makes sense. I'm mostly leaning towards just integrating whole Workout Planner into the Web Editor. So that the Web Editor would have 2 modes - Simple and Advanced, and Simple is basically what Workout Planner currently is. You can edit your whole program there, and e.g. open it and quickly add a line to a day you care about, like you shown above  `Bench Press / 5 @8, 3 @9, 1 @10, 5x5 50%`. Then save, and it'll save it and reapply the changes to any ongoing workouts, etc.

**Comment by astashov** [comment]
Okay, now the workout planner is fully integrated into the app, so I can close it.
