### ISSUE TITLE
[Feature request] Bring the notes from last exercice to the current exercice

### ISSUE THREAD

**Issue by Sni3rs** [astashov/liftosaur#71]
Hi Anton,

When I add note in a specific exercise during the workout, It would be useful to retrieve it directly in the current one - like you do with the last weights.
Also, adding the last time to perform this day in the top menu could be good!

## The note section I'm talking about
![image](https://github.com/astashov/liftosaur/assets/89201449/dabaa388-27d9-45bb-b45a-0b181569a363)

## Last exercises weights/rep/... display
![image](https://github.com/astashov/liftosaur/assets/89201449/10dfdf95-258e-41b9-b0b4-4a21da50c545)

Maybe add the "last exercise comment" just below?

## The last duration time could be displayed just after the "start" ?
![image](https://github.com/astashov/liftosaur/assets/89201449/37b91113-4469-4f84-8736-2613882a4cda)

**Comment by astashov** [comment]
Moved to the feature request: https://github.com/astashov/liftosaur/discussions/126
