### ISSUE TITLE
[Feature request] Ability to add our own exercice image

### ISSUE THREAD

**Issue by Sni3rs** [astashov/liftosaur#72]
Can you add the ability to add our own exercises images? I have few "personal" exercises and would love to have the image displayed somewhere

![image](https://github.com/astashov/liftosaur/assets/89201449/8cb41ce8-36ec-4a20-a1d1-c66a7fffe47c)

**Comment by astashov** [comment]
Yeah, it's a popular request, will eventually add!

**Comment by astashov** [comment]
Added
