### ISSUE TITLE
[Feature Request] Material dependent unit (Metric or imperial)

### ISSUE THREAD

**Issue by RlndVt** [astashov/liftosaur#76]
In the gyms I've seen, while barbells/dumbbells are usually in metric, cable and other machines are always in imperial (with a conversion to metric).

Would be nice to be able to specify weight increments in lbs, even though I've setup the app to use metric.

**Comment by astashov** [comment]
I have plans to allow to specify units per equipment, that should probably solve the problem...

**Comment by astashov** [comment]
Moved to the feature request: https://github.com/astashov/liftosaur/discussions/134
