### ISSUE TITLE
[Feature Request] Automatically Use minReps When Using Rep Ranges

### ISSUE THREAD

**Issue by youhavejameswoods** [astashov/liftosaur#77]
Today, using Rep Ranges seems to necessitate the need to use custom progression scripts.  If one is using rep ranges, they would most likely consider success to be anywhere in and above the range (i.e., >= minReps).  

Automatically leveraging minReps when Rep Ranges are in use would greatly simplify the code required to be written for lifting programs.

**Comment by astashov** [comment]
Usually you want to increase weight when you hit the upper limit though, right? Like the standard double progression - you have a range 8-12, and once you hit 12, you bump up the weight. Currently you can do it like `Squat / 3x8-12 / progress: lp(5lb)`.

But you want to increase the weight when you hit min reps in the range ,right?

**Comment by youhavejameswoods** [comment]
Is there a plan to implement this at some point in the future? Mainly asking because I’m considering transitioning my programs from the legacy versions to new, but I’ll hold off a bit if this is a future enhancement since it’ll cut down on custom code significantly (I think it’ll actually remove the need for any custom code for progressions for me). 
Thanks!

**Comment by astashov** [comment]
Currently, if you use rep ranges with `progress: lp`, then it uses the top of the range to make a decision if you need to bump up the weight, and the bottom of range to make a decision if you need to reduce the weight. I.e. if you have `Squat / 3x8-12 / progress: lp(5lb, 1, 0, 10lb, 1, 0)`, then it'll increase the weight if you hit 12 on all the sets, and will reduce the weight if at least one of the sets is below 8.

I think the logic makes sense, and frankly if I change it - it's going to be a breaking change for a lot of people. So, in your case I'd recommend to still use a custom progressions. Something like this:

```
Squat / 4x8-12 / progress: custom() {~
  if (completedReps[1] >= reps[1] && completedReps >= minReps) {
    weights += 5lb
  }
~}
```
That would make sure you hit the max rep on the first set, and the rest of the sets are at least within the rep range.
You could reuse the logic in all the rest of your exercises, like:

```
Bench Press /  4x8-12 / progress: custom() { ...Squat }
```

**Comment by astashov** [comment]
You can kinda do that right now, with creating a non used exercise, and reuse its progress:

```
my_very_cool_progression: Squat / 1x1 / used: none / progress: custom() {~
  // your logic
~}

Bench Press / 3x8 / progress: { ...my_very_cool_progression: Squat }
```
