### ISSUE TITLE
[Bug] Closing the Edit Box Saves Weight Change

### ISSUE THREAD

**Issue by OpenSauce** [astashov/liftosaur#83]
Me again, another thing I noticed. When modifying the exercise weight within a workout, if you click the cross (and not done) it will still update the weight, I would expect the changes to only apply if clicking done, and not clicking cross.

Steps to reproduce:
1. Modify weight of an exercise within a workout
2. Modify the value
3. Click the cross, the weight update should still commit

**Comment by astashov** [comment]
That was the UI dilemma :) Since that modal is also used as an entrypoint into program editing - having 3 buttons (only in workout, in a program, save) would be button overloading :) So I decided to just change the state vars in place right away, without confirmation.
