### ISSUE TITLE
Run a progression on an exercise only if more than 0 sets finished in a workout

### ISSUE THREAD

**Issue by youhavejameswoods** [astashov/liftosaur#84]
As a Liftosaur user, 
I’d like the progression script to only be run on exercises with >0 sets for the workout,
so that ‘current decrease attempt’, ‘current increase attempts’, and/or weight isn’t changed when an exercise isn’t performed during a workout and I won’t  have to manually update my program with the prior values after my workout is completed.

**Comment by astashov** [comment]
Fixed by 11423d64f2dd6326310959c9714dd8543771182c
