### ISSUE TITLE
[Bug] can't finish workout

### ISSUE THREAD

**Issue by jm96441n** [astashov/liftosaur#95]
After the recent update I haven't been able to finish my workout. I attached a video showing it.
https://github.com/astashov/liftosaur/assets/16313206/0f08303b-4c34-4b21-8d64-4713ac2c1a34

**Comment by astashov** [comment]
Could you send me your email you used to sign up to info@liftosaur.com please?

**Comment by astashov** [comment]
Could you also try to switch to program screen, Save, the try to finish again?

**Comment by jm96441n** [comment]
oh weird, switching to the program screen and hitting save and then hitting finish solved it!
