### ISSUE TITLE
Multiple descriptions with repeat syntax

### ISSUE THREAD

**Issue by wkeahi** [astashov/liftosaur#97]
When using multiple descriptions with a repeated exercise, the description gets merged. MWE:

```
# Week 1
## Day 1
//Desc 1

//Desc 2
Squat[1, 1-3] / 3x5

# Week 2
## Day 1

# Week 3
## Day1
```

Before completing sets, all three days show "Desc 1." After completing Week 1, Day 1, the next week shows "Desc 1 Desc 2."

**Comment by astashov** [comment]
Fixed!
